---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# blblm

<!-- badges: start -->
<!-- badges: end -->

The goal of blblm is to easily perform bootstraps integrated with LM and GLM

## Installation

You can install the released version of blblm from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("blblm")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("fburrell/141CProj")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
#below are some helpful examples about using the package 

library(blblm)
#non parallel lm 
l<-blblm(wt~mpg,mtcars, 1000)
coeff.blb(l)
se.blb(l)
predicts.blb(l, data.frame(wt = c(2.5, 3), mpg=c(20,30)), confidence=TRUE)
confints.blb(l, level=0.9)


#parallel lm
l<-parr.blblm(wt~mpg,mtcars,1000,4)
coeff.blb(l)
se.blb(l)
predicts.blb(l, data.frame(wt = c(2.5, 3), mpg=c(20,30)), confidence=TRUE)
confints.blb(l, level=0.9)

#non parallel glm
df<-data.frame(Titanic)
l<-blbglm(Survived~Class+Sex, binomial, df,1000)
coeff.blb(l)
se.blb(l)
confints.blb(l, level=0.9)


#parallel glm
l<-parr.blbglm(Survived~Class+Sex, binomial, df,1000, 4)
coeff.blb(l)
se.blb(l)
confints.blb(l, level=0.9)

```
